apiVersion: v1
kind: Pod
metadata:
  namespace: profiler
  name: simpleprofiler-server
  labels:
    app: profiler
    profiler: server
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 2000
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: profiler-server
  containers:
  - name: profiler
    imagePullPolicy: Always
    image: francistor/simpleprofiler:0.2
    args: ["-server", "-serverport", "8080", "-sync"]
    ports:
        - containerPort: 80
          name: "http-server"
    volumeMounts:
    - mountPath: "/tmp/simpleprofiler"
      name: pvc-volume