apiVersion: v1
kind: Pod
metadata:
  namespace: profiler
  name: simpleprofiler-client
  labels:
    app: profiler
    profiler: client
spec:
  restartPolicy: Never
  containers:
  - name: profiler
    imagePullPolicy: Always
    image: francistor/simpleprofiler:0.2
    args: ["-client", "-serverhost", "profiler", "-serverport", "8080", "-sync"]