apiVersion: v1
kind: Pod
metadata:
  namespace: profiler
  name: simpleprofiler-server
  labels:
    app: profiler
    profiler: server
spec:
  restartPolicy: Never
  containers:
  - name: profiler
    imagePullPolicy: Always
    image: francistor/simpleprofiler:0.2
    args: ["-server", "-serverport", "8080", "-sync"]
    ports:
        - containerPort: 80
          name: "http-server"