apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.26.6"
controlPlaneEndpoint: "192.168.122.2:6443"
networking:
  podSubnet: "10.251.0.0/16"
  serviceSubnet: "10.252.0.0/16"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
cgroupDriver: systemd
