# This job populates and starts replication from another mysql instance previously configured
# To be used after loss of one instance

apiVersion: batch/v1
kind: Job
metadata:
  name: main-reconfig
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        job: main-reconfig
    spec:
      restartPolicy: Never
      containers:
      - name: config-main
        image: mysql:8.0.32
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root-password
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: replication-password
        command:
        - bash
        - "-c"
        - |
          #!/bin/bash

          # Exit on error
          set -e

          export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
          export MYSQL_REPLICATION_PASSWORD=$MYSQL_REPLICATION_PASSWORD
          export MYSQL_OTHER_HOST=mysql-main-0.mysql-main
          export MYSQL_THIS_HOST=mysql-main-1.mysql-main

          echo "started at $(date)"

          export MYSQL_PWD=$MYSQL_ROOT_PASSWORD

          # Block inserts on this node
          # TODO


          # Stop replica on the other node
          echo "
          STOP REPLICA;
          RESET REPLICA;
          "| MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql -h $MYSQL_OTHER_HOST -u root --force
          
          # Backup from master and restore here.
          MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysqldump --all-databases -flush-privileges --single-transaction --flush-logs --triggers --routines --events -hex-blob --host=$MYSQL_OTHER_HOST --user=root > backup.sql
          cat backup.sql | MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql --init-command="SET autocommit=0;" -h $MYSQL_THIS_HOST  -u root 

          echo "backup/restore performed at $(date)"
        
          # Need to do FLUSH PRIVILEGES before granting permissions. Don't know why
          echo "
            FLUSH PRIVILEGES;
            GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';
            FLUSH PRIVILEGES;
          " | MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql -h $MYSQL_THIS_HOST -u root 

          # Configure replica
          echo "
          CHANGE REPLICATION SOURCE TO
            SOURCE_USER='replication_user',
            SOURCE_PASSWORD=\"$MYSQL_REPLICATION_PASSWORD\",
            SOURCE_HOST=\"$MYSQL_OTHER_HOST\",
            SOURCE_AUTO_POSITION=1
            FOR CHANNEL 'main';
            
            START REPLICA;
          "| MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql -h $MYSQL_THIS_HOST -u root 

          echo "replica configured"
          echo "replica configured" >> /tmp/reconfig.log

          # Start replica on the other node
          echo "
          CHANGE REPLICATION SOURCE TO
            SOURCE_USER='replication_user',
            SOURCE_PASSWORD=\"$MYSQL_REPLICATION_PASSWORD\",
            SOURCE_HOST=\"$MYSQL_THIS_HOST\",
            SOURCE_AUTO_POSITION=1
            FOR CHANNEL 'main';
            
            START REPLICA;
          "| MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql -h $MYSQL_OTHER_HOST -u root 

          echo "finished"
