# This job populates and starts replication from another mysql instance

apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: config-main
        image: mysql:8.0.32
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root-password
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: replication-password
        command:
        - bash
        - "-c"
        - |
          #!/bin/bash

          

    