FROM ubuntu
# To avoid user interaction
ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y curl

# Install go
RUN curl -L -o go.tar.gz https://go.dev/dl/go1.17.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go.tar.gz && echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/environment

# Copy contents
RUN mkdir -p /simpleprofiler/bin
COPY *.go go.mod go.sum *.pem /simpleprofiler/bin/
RUN cd /simpleprofiler/bin && /usr/local/go/bin/go build