apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mypvc
spec:
 storageClassName: rook-ceph-block-retain
 volumeName: pvc-9b970bdd-cead-4c63-920b-523041033546
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
